config/routes.rb
Rails.application.routes.draw do
  root 'organizations#index'

  get '/user_protocols', to: 'user_protocols#index', as: :protocols
  delete '/user_protocols', to: 'user_protocols#destroy_all', as: :protocols_destroy_all

  get 'dj_manager/index', as: :dj_index
  get 'dj_manager/:id' => "dj_manager#show", as: :dj_show

  post 'dj_manager/create_planner' => "dj_manager#create_planner", as: :dj_create_planner
  delete 'dj_manager/:id/destroy' => "dj_manager#destroy", as: :dj_delete
  delete 'dj_manager/destroy_all', as: :dj_delete_all

  resources :option_sets
  resources :services do
    collection do
      get 'datatable' # pagination
    end
    member do
      get 'legalise'
      get 'unlegalise'
    end
  end
  resources :jobs do
    member do
      get 'scan'
    end
  end
  resources :schedules
  resources :users
  resources :scanned_ports do
    collection do
      get 'datatable' # pagination
    end
  end
  resources :organizations do
    member do
      post 'report'
    end
  end

  resources :user_sessions, only: [:create, :destroy]

  delete '/sign_out', to: 'user_sessions#destroy', as: :sign_out
  get '/sign_in', to: 'user_sessions#new', as: :sign_in

  resource :users_roles

  get '/service_tasks', to: 'service_tasks#index', as: :service_tasks
  post '/service_tasks/clean_base', to: 'service_tasks#clean_base', as: :clean_base_task
  post '/service_tasks/sqlite_backup', to: 'service_tasks#sqlite_backup', as: :sqlite_backup_task

  get '/detected_services', to: 'dashboard#detected_services', as: :detected_services
  get '/dashboard/datatable', to: 'dashboard#datatable'
  get '/dashboard/datatable2', to: 'dashboard#datatable2'
  get '/new_services', to: 'dashboard#new_services', as: :new_services
  get '/hosts', to: 'dashboard#hosts', as: :hosts

end

app/models/service.rb
class Service < ActiveRecord::Base
  include Datatableable

  IP4_REGEXP = /(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}
               ([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])/x
  WRONG_IP4_REGEXP = /(\d+\.){3}\d+/
  IP4_CIDR_REGEXP = /(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}
                    ([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])
                    (\/([0-9]|[1-2][0-9]|3[0-2]))/x
  IP4_D_REGEXP = /(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5]))/ # valid IP4 part like 192 or 10 or 1
  IP4_D1_2_REGEXP = /(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){2}/
  IP4_D1_3_REGEXP = /(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}/
  IP4_D4_REGEXP = /([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])/
  IP4_RANGE1_REGEXP = /^\s*(?<start_ip_d1>#{IP4_D_REGEXP})\.
                       (?<start_ip_d2>#{IP4_D_REGEXP})\.
                       (?<start_ip_d3>#{IP4_D_REGEXP})\.
                       (?<start_ip_d4>#{IP4_D_REGEXP})-
                       (?<end_ip_d1>#{IP4_D_REGEXP})\.
                       (?<end_ip_d2>#{IP4_D_REGEXP})\.
                       (?<end_ip_d3>#{IP4_D_REGEXP})\.
                       (?<end_ip_d4>#{IP4_D_REGEXP})\s*$
                      /x

  DNS_NAME_REGEXP = /(([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]*[a-zA-Z0-9])\.)*([A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9\-]*[A-Za-z0-9])/

  PROTOCOLS = ['tcp', 'udp']

  LEGALITIES = {1 => I18n.t('messages.message_yes'), 0 => I18n.t('messages.message_no')}

  belongs_to :organization

  validates :name, length: {minimum: 3, maximum: 255}
  validates :name, uniqueness: {scope: [:port, :host, :protocol]}, allow_blank: true

  validates :port, uniqueness: {scope: [:host, :protocol]}
  validates :port, numericality: {only_integer: true}, allow_blank: true
  validates :port, inclusion: {in: 0..65535}, allow_blank: true

  validate :host_is_ip4_or_range
  validates :host, uniqueness: {scope: [:port, :protocol]}

  validates :protocol, uniqueness: {scope: [:port, :host]}, allow_blank: true
  validates :protocol, inclusion: {in: PROTOCOLS}, allow_blank: true

  def self.ip4_regexp
    IP4_REGEXP
  end

  def self.wrong_ip4_regexp
    WRONG_IP4_REGEXP
  end

  def self.ip4_cidr_regexp
    IP4_CIDR_REGEXP
  end

  def self.ip4_range1_regexp
    IP4_RANGE1_REGEXP
  end

  def self.ip4_d_regexp
    IP4_D_REGEXP
  end

  def self.ip4_d1_2_regexp
    IP4_D1_2_REGEXP
  end

  def self.ip4_d1_3_regexp
    IP4_D1_3_REGEXP
  end

  def self.ip4_d4_regexp
    IP4_D4_REGEXP
  end

  def self.dns_name_regexp
    DNS_NAME_REGEXP
  end

  def self.legalities
    LEGALITIES
  end

  def self.protocols
    PROTOCOLS
  end

  def self.show_legality(legality)
    if legality == 1
      I18n.t('messages.message_yes')
    elsif legality == 0
      I18n.t('messages.message_no')
    else
      I18n.t('messages.unknown')
    end
  end

  def show_legality
    if self.legality?
      I18n.t('messages.message_yes')
    else
      I18n.t('messages.message_no')
    end
  end

  def show_host
    if port.present?
      ''
    else
        I18n.t('activerecord.attributes.scanned_port.host')
    end
  end

  def self.legality_key(state, host, port, protocol)
    service = Service.where(host: host, port: port, protocol: protocol).first
    if state == :closed
      legality = 3 # no means
    else
      if service.present?
        if service.legality == 1
          legality = 1 # true
        else
          legality = 0 #false
        end
      else
        legality = 2 # unknown
      end
    end
    legality
  end

  # Make array of ip addresses from array of ip adddresses and ip ranges
  # Example:
  #   Service.normilized_hosts(['192.168.1.1', '192.168.1.2-192.168.1.3', '172.16.1-2']) ->
  #   ['192.168.1.1', '192.168.1.2', '192.168.1.3', '172.16.1.1', '172.16.1.2']
  def self.normilize_hosts(hosts)
    normilized_hosts = []
    hosts.each do |host|
      if /\A(#{ip4_regexp})-(#{ip4_regexp})\z/ =~ host
        range = /\A(?<start_ip>#{ip4_regexp})-(?<end_ip>#{ip4_regexp})\z/.match(host)
        normilized_hosts += (IPAddr.new(range[:start_ip])..IPAddr.new(range[:end_ip])).map(&:to_s).to_a
      elsif /\A(#{ip4_regexp})\z/ =~ host
        normilized_hosts << host
      elsif /\A(#{Service.ip4_d1_3_regexp})(#{Service.ip4_d4_regexp})-(#{Service.ip4_d4_regexp})\z/ =~ host
        range2 = /\A(?<start_ip_d1_3>#{Service.ip4_d1_3_regexp})(?<start_ip_d4>#{Service.ip4_d4_regexp})-(?<end_ip_d4>#{Service.ip4_d4_regexp})\z/.match(host)
        normilized_hosts += (IPAddr.new(range2[:start_ip_d1_3] << range2[:start_ip_d4])..IPAddr.new(range2[:start_ip_d1_3] << range2[:end_ip_d4])).map(&:to_s).to_a
      end
    end
    normilized_hosts.uniq
  end

  private

  def host_is_ip4_or_range
    range = /\A\s*(?<start_ip>#{Service.ip4_regexp})-(?<end_ip>#{Service.ip4_regexp})\s*\z/.match(host)
    range2 = /\A\s*(?<start_ip_d1_3>#{Service.ip4_d1_3_regexp})(?<start_ip_d4>#{Service.ip4_d4_regexp})-(?<end_ip_d4>#{Service.ip4_d4_regexp})\s*\z/.match(host)
    unless /\A\s*#{Service.ip4_regexp}\s*\z/ =~ host || range || range2
      errors[:host] << I18n.t('errors.messages.must_be_ip4_or_range')
    end
    # check the second ip in range is greater then the first ip
    if range
      if IPAddr.new(range[:start_ip]).to_i > IPAddr.new(range[:end_ip]).to_i
        errors[:host] << I18n.t('errors.messages.must_be_ip4_or_range')
      end
    elsif range2
      if range2[:start_ip_d4].to_i > range2[:end_ip_d4].to_i
        errors[:host] << I18n.t('errors.messages.must_be_ip4_or_range')
      end
    end
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: [:show, :edit, :update, :destroy, :legalise, :unlegalise]
  before_action :set_organizations, only: [:new, :create, :edit, :update, :legalise, :unlegalise]
  before_action :set_previous_action, only: [:new, :edit, :destroy]
  before_action :reset_previous_action, only: [:index]

  # GET /services
  # GET /services.json
  def index
    authorize Service
    #@services = policy_scope(Service).includes(:organization)
  end

   def datatable
    authorize Service
    allowed_services_ids = policy_scope(Service).pluck(:id)
    fields = [{field: 'organizations.name',
               as: 'organization_name',
               joins: 'organizations',
               on: 'organizations.id = services.organization_id'}]
    fields << if current_user.has_any_role? :admin, :editor, :viewer
              {field: 'organizations.id',
               as: 'organization_id',
               invisible: true}
              else
              {field: 'organizations.id',
               as: 'organization_id',
               invisible: true,
               filter: "services.id IN (#{allowed_services_ids.join(',')})"}
              end
    fields += [{field: 'services.id', as: 'service_id', invisible: true},
              {field: 'services.name', as: 'service_name'},
              {field: 'services.port', as: 'service_type',
                map_by_sql: %Q| CASE
                                WHEN services.port IS NULL THEN '#{I18n.t('activerecord.attributes.scanned_port.host')}'
                                ELSE '' END
                              |},
              {field: 'services.legality', as: 'service_legality', map_to: Service.legalities},
              {field: 'services.host', as: 'service_host'},
              {field: 'services.port', as: 'service_port',
              map_by_sql: "'<' || services.port || '>'"},
              {field: 'services.protocol', as: 'service_protocol'}]
    @datatable = Service.dt_all(params, fields)
    respond_to do |format|
      format.json {render 'datatable'}
    end
  end

  # GET /services/1
  # GET /services/1.json
  def show
    authorize @service
  end

  # GET /services/new
  def new
    authorize Service
    if params[:service].present?
      @service = Service.new(organization_id: params[:service][:organization_id],
                             host: params[:service][:host],
                             port: params[:service][:port],
                             protocol: params[:service][:protocol],
                             name: params[:service][:service])
    else
      @service = Service.new
    end
  end

  # GET /services/1/edit
  def edit
    authorize @service
  end

  # POST /services
  # POST /services.json
  def create
    @service = Service.new(service_params)
    authorize @service

    respond_to do |format|
      if @service.save
        flash[:success] = t('flashes.create', model: Service.model_name.human)
        format.html { redirect_to session.delete(:return_to) || services_path }
        format.json { render :show, status: :created, location: @service }
        protocol_action("создание сервиса #{@service.name}")
      else
        format.html { render :new }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  def legalise
    authorize @service
    @service.update_attribute :legality, 1
    protocol_action("легализация сервиса #{@service.name}")
    render 'dashboard/detected_services_renew'
  end

  def unlegalise
    authorize @service
    @service.update_attribute :legality, 0
    protocol_action("делегализация сервиса #{@service.name}")
    render 'dashboard/detected_services_renew'
  end

  # PATCH/PUT /services/1
  # PATCH/PUT /services/1.json
  def update
    authorize @service
    respond_to do |format|
      if @service.update(service_params)
        flash[:success] = t('flashes.update', model: Service.model_name.human)
        format.html { redirect_to session.delete(:return_to) || services_path }
        format.json { render :show, status: :ok, location: @service }
        protocol_action("редактирование сервиса #{@service.name}")
      else
        format.html { render :edit }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /services/1
  # DELETE /services/1.json
  def destroy
    authorize @service
    @service.destroy
    protocol_action("удаление сервиса #{@service.name}")
    respond_to do |format|
      flash[:success] = t('flashes.destroy', model: Service.model_name.human)
      format.html { redirect_to session.delete(:return_to) }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_service
    @service = Service.find(params[:id])
  end

  def set_organizations
    @organizations = policy_scope(Organization).order(:name)
    @user_active_services = current_user.jobs_active_services
  end

  def set_previous_action
      session[:return_to] ||= request.env['HTTP_REFERER']
  end

  def reset_previous_action
      session.delete(:return_to)
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def service_params
    params.require(:service).permit(:name, :organization_id, :legality, :host, :port, :protocol, :description)
  end
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/services/_form.html.slim
= form_for @service, html: {class: 'form-horizontal'} do |f|
  - if @service.errors.any?
    .col-sm-offset-1.col-sm-11
      #error_explanation
        h2 = t('errors.template.header', count: @service.errors.count, model: Service.model_name.human)
        ul
          - @service.errors.full_messages.each do |message|
            li = message
  .form-group
    = f.label :name, class: 'col-sm-2 control-label required'
    .col-sm-10
        = f.text_field :name, class: 'form-control', placeholder: 'название'
  .form-group
    = f.label :organization_id, class: 'col-sm-2 control-label required'
    .col-sm-10
      = f.collection_select :organization_id, @organizations, :id, :name, class: 'form-control'
  .form-group
    = f.label :host, class: 'col-sm-2 control-label required'
    .col-sm-10
      = f.text_field :host, class: 'form-control', placeholder: 'IP адрес хоста или диапазон (192.168.1.1 или 172.16.1-32 или 192.168.1.1-192.168.1.255)'
  .form-group
    = f.label :port, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :port, class: 'form-control', placeholder: 'номер порта (от 0 до 65535)'
  .form-group
    = f.label :protocol, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.select :protocol, Service.protocols, class: 'form-control', include_blank: true
  .form-group
    = f.label :description, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_area :description, rows: 6, class: 'form-control', placeholder: 'дополнительная информация'
  .form-group
    .col-sm-offset-2.col-sm-10
      .checkbox
         label
           = f.check_box :legality
           | #{t('activerecord.attributes.service.legality')}
  .actions.form-group
    .col-sm-offset-2.col-sm-10
      => link_to session[:return_to] do
        span.btn.btn-info = t('actions.back')
      = f.submit t('actions.create'), class: 'btn btn-success'

app/views/services/_organization_detected_services.html.slim
br
table.display.table.table-striped.table-bordered#index_table
  thead
    tr
      th = t('activerecord.attributes.scanned_port.job_time')
      th = t('activerecord.attributes.scanned_port.job_id')
      th = t('activerecord.attributes.scanned_port.host')
      th = t('activerecord.attributes.scanned_port.port')
      th = t('activerecord.attributes.scanned_port.protocol')
      th = t('activerecord.attributes.scanned_port.state')
      th = t('activerecord.attributes.service.legality')
      th = t('activerecord.attributes.scanned_port.legality')
      th = t('activerecord.attributes.scanned_port.service')
      th = t('activerecord.attributes.scanned_port.product')
      th

  tbody
    - @active_services.each do |scanned_port|
      tr
        td = scanned_port.job_time.strftime("%d.%m.%Y-%H.%m.%S")
        td = scanned_port.job.name
        td = scanned_port.host
        td = "<#{scanned_port.port}>"
        td = scanned_port.protocol
        td = scanned_port.show_state
        td = Service.show_legality(scanned_port.s_legality)
        td = scanned_port.show_legality
        td = scanned_port.service
        td = scanned_port.show_product
        td
          - if scanned_port.s_legality.present?
            = link_to service_path(scanned_port.s_id.to_i), class: 'btn btn-default btn-xs', 'data-toggle' => 'tooltip', 'data-placement' => 'top', title: t('actions.view') do
              i.glyphicon.glyphicon-info-sign aria-hidden="true"
          - else
            = link_to new_service_path(service: {organization_id: @organization.id, host: scanned_port.host, port: scanned_port.port, protocol: scanned_port.protocol, service: "#{scanned_port.service} #{@organization.name}"}), class: 'btn btn-default btn-xs', 'data-toggle' => 'tooltip', 'data-placement' => 'top', title: t('helpers.submit.create', model: Service.model_name.human) do
              span.text-info
                i.glyphicon.glyphicon-plus-sign aria-hidden="true"

app/views/services/_organization_hosts.html.slim
br
table.display.table.table-striped.table-bordered#index_table
  thead
    tr
      th.w30 = t('activerecord.attributes.service.name')
      th.w30 = t('activerecord.attributes.service.host')
      th

  tbody
    - @hosts.each do |host|
      tr
        td = host.name
        td
          = host.host
          = link_to new_job_path(job: {organization_id: @organization.id, host: host.host}), class: 'btn btn-link btn-xs', 'data-toggle' => 'tooltip', 'data-placement' => 'top', title: t('helpers.submit.create', model: Job.model_name.human) do
            span.text-success
              i.glyphicon.glyphicon-plus-sign aria-hidden="true"
        td
          = link_to host, class: 'btn btn-default btn-xs', 'data-toggle' => 'tooltip', 'data-placement' => 'top', title: t('actions.view') do
            i.glyphicon.glyphicon-info-sign aria-hidden="true"
          = link_to edit_service_path(host), class: 'btn btn-default btn-xs', 'data-toggle' => 'tooltip', 'data-placement' => 'top', title: t('actions.edit') do
            i.glyphicon.glyphicon-edit aria-hidden="true"
          = link_to host, data: {:confirm => t('actions.confirm')}, :method => :delete, class: 'btn btn-default btn-xs', 'data-toggle' => 'tooltip', 'data-placement' => 'top', title: t('actions.delete') do
            i.glyphicon.glyphicon-trash aria-hidden="true"

= link_to new_service_path(service: {organization_id: @organization.id}) do
    span.btn.btn-success = t('helpers.submit.create', model: Service.model_name.human)

app/views/services/_organization_scans.html.slim
br
table.display.table.table-striped.table-bordered#index_table
  thead
    tr
      th = t('activerecord.attributes.scanned_port.job_time')
      th = t('activerecord.attributes.scanned_port.job_id')
      th = t('activerecord.attributes.scanned_port.host')
      th = t('activerecord.attributes.scanned_port.port')
      th = t('activerecord.attributes.scanned_port.protocol')
      th = t('activerecord.attributes.scanned_port.state')
      th = t('activerecord.attributes.service.legality')
      th = t('activerecord.attributes.scanned_port.legality')
      th = t('activerecord.attributes.scanned_port.service')
      th = t('activerecord.attributes.scanned_port.product')
      th

  tbody
    - @scans.each do |scanned_port|
      tr
        td = scanned_port.job_time.strftime("%d.%m.%Y-%H.%m.%S")
        td = scanned_port.job.name if scanned_port.job
        td = scanned_port.host
        td = "<#{scanned_port.port}>"
        td = scanned_port.protocol
        td = scanned_port.show_state
        td = Service.show_legality(scanned_port.s_legality)
        td = scanned_port.show_legality
        td = scanned_port.service
        td = scanned_port.show_product
        td
          - if scanned_port.s_legality.present?
            = link_to service_path(scanned_port.s_id.to_i), class: 'btn btn-default btn-xs', 'data-toggle' => 'tooltip', 'data-placement' => 'top', title: t('actions.view') do
              i.glyphicon.glyphicon-info-sign aria-hidden="true"
          - else
            = link_to new_service_path(service: {organization_id: @organization.id, host: scanned_port.host, port: scanned_port.port, protocol: scanned_port.protocol, service: "#{scanned_port.service} #{@organization.name}"}), class: 'btn btn-default btn-xs', 'data-toggle' => 'tooltip', 'data-placement' => 'top', title: t('helpers.submit.create', model: Service.model_name.human) do
              span.text-info
                i.glyphicon.glyphicon-plus-sign aria-hidden="true"

app/views/services/_organization_services.html.slim
br
table.display.table.table-striped.table-bordered#index_table
  thead
    tr
      th = t('activerecord.attributes.service.name')
      th = t('activerecord.attributes.scanned_port.host')
      th = t('activerecord.attributes.scanned_port.port')
      th = t('activerecord.attributes.scanned_port.protocol')
      th = t('activerecord.attributes.service.legality')
      th

  tbody
    - @services.each do |service|
      tr
        td = service.name
        td = service.host
        td = service.port
        td = service.protocol
        td = service.show_legality
        td
          = link_to service, class: 'btn btn-default btn-xs', 'data-toggle' => 'tooltip', 'data-placement' => 'top', title: t('actions.view') do
            i.glyphicon.glyphicon-info-sign aria-hidden="true"
          = link_to edit_service_path(service), class: 'btn btn-default btn-xs', 'data-toggle' => 'tooltip', 'data-placement' => 'top', title: t('actions.edit') do
            i.glyphicon.glyphicon-edit aria-hidden="true"
          = link_to service, data: {:confirm => t('actions.confirm')}, :method => :delete, class: 'btn btn-default btn-xs', 'data-toggle' => 'tooltip', 'data-placement' => 'top', title: t('actions.delete') do
            i.glyphicon.glyphicon-trash aria-hidden="true"

= link_to new_service_path(service: {organization_id: @organization.id}) do
    span.btn.btn-success = t('helpers.submit.create', model: Service.model_name.human)

app/views/services/datatable.json.erb
<%= dt_response(@datatable) do |new_row, row| %>
  <% new_row << "<a href='/organizations/#{row.organization_id}' class='btn btn-link btn-xs'> #{row.organization_name}</a>" %>
  <% new_row << row.service_name %>
  <% new_row << row.service_type %>
  <% new_row << row.service_legality %>
  <% new_row << row.service_host %>
  <% new_row << row.service_port %>
  <% new_row << row.service_protocol %>
  <% new_row << %Q(
                  <a class='btn btn-default btn-xs'
                    data-toggle='tooltip'
                    data-placement='top'
                    title='#{t('actions.view')}'
                    href='/services/#{row.service_id}'>
                    <i aria-hidden='true'
                      class='glyphicon glyphicon-info-sign'>
                    </i>
                  </a>
                  <a class='btn btn-default btn-xs'
                    data-toggle='tooltip'
                    data-placement='top'
                    title='#{t('actions.edit')}'
                    href='/services/#{row.service_id}/edit'>
                    <i aria-hidden='true'
                      class='glyphicon glyphicon-edit'>
                    </i>
                  </a>
                  <a data-confirm='#{t('actions.confirm')}'
                    class='btn btn-default btn-xs'
                    data-toggle='tooltip'
                    data-placement='top'
                    title='#{t('actions.delete')}'
                    rel='nofollow' data-method='delete'
                    href='/services/#{row.service_id}'>
                     <i aria-hidden='true'
                      class='glyphicon glyphicon-trash'>
                     </i>
                  </a>
                  ) %>
<% end %>

app/views/services/edit.html.slim
.col-sm-offset-1.col-sm-11
  h3
    span.text-primary = "#{t('actions.edit')} #{Service.model_name.human}"

== render 'form'

app/views/services/index.html.slim
h3
  span.text-primary
    = Service.model_name.human count: 2

= dt_big_table([{name: t('activerecord.attributes.service.organization_id'), sort: :desc, html_class: 'w25'},\
                {name: t('activerecord.attributes.service.name'), html_class: 'w25'},\
                {name: t('activerecord.attributes.scanned_port.host'), html_class: 'w5'},\
                {name: t('activerecord.attributes.service.legality'), html_class: 'w10'},\
                {name: t('activerecord.attributes.service.host'), html_class: 'w15'},\
                {name: t('activerecord.attributes.service.port'), html_class: 'w5'},\
                {name: t('activerecord.attributes.service.protocol'), html_class: 'w5'},\
                {name: '', html_class: 'w10'}],\
               '/services/datatable')

br

= link_to new_service_path do
  span.btn.btn-success = t('helpers.submit.create', model: Service.model_name.human)
    i.glyphicon.glyphicon-info-sign aria-hidden="true"

app/views/services/new.html.slim
.col-sm-offset-1.col-sm-11
  h3
    span.text-primary = "#{t('actions.new')} #{Service.model_name.human}"

== render 'form'

app/views/services/show.html.slim
.col-sm-offset-1.col-sm-11
  table.table.table-striped.table-hover
    caption.text-primary
      h3 = Service.model_name.human
    thead
      th.col-md-1
      th.col-md-7
    tbody
      tr
        td.text-right.text-info
          strong
            = Service.human_attribute_name :name
        td
          = @service.name
      tr
        td.text-right.text-info
          strong
            = Service.human_attribute_name :organization_id
        td
          = link_to @service.organization.name, @service.organization, class: 'btn btn-link btn-xs'
      tr
        td.text-right.text-info
          strong
            = Service.human_attribute_name :host_ip
        td
          = @service.host
      tr
        td.text-right.text-info
          strong
            = Service.human_attribute_name :port
        td
          = @service.port
      tr
        td.text-right.text-info
          strong
            = Service.human_attribute_name :protocol
        td
          = @service.protocol
      tr
        td.text-right.text-info
          strong
            = Service.human_attribute_name :legality
        td
          = @service.show_legality
      tr
        td.text-right.text-info
          strong
            = Service.human_attribute_name :description
        td
          = simple_format @service.description

  => link_to services_path do
    span.btn.btn-info
      = Service.model_name.human count: 2
  = link_to edit_service_path(@service) do
    span.btn.btn-warning
      = t('actions.edit')