config/routes.rb
Rails.application.routes.draw do
  root 'organizations#index'

  get '/user_protocols', to: 'user_protocols#index', as: :protocols
  delete '/user_protocols', to: 'user_protocols#destroy_all', as: :protocols_destroy_all

  get 'dj_manager/index', as: :dj_index
  get 'dj_manager/:id' => "dj_manager#show", as: :dj_show

  post 'dj_manager/create_planner' => "dj_manager#create_planner", as: :dj_create_planner
  delete 'dj_manager/:id/destroy' => "dj_manager#destroy", as: :dj_delete
  delete 'dj_manager/destroy_all', as: :dj_delete_all

  resources :option_sets
  resources :services do
    collection do
      get 'datatable' # pagination
    end
    member do
      get 'legalise'
      get 'unlegalise'
    end
  end
  resources :jobs do
    member do
      get 'scan'
    end
  end
  resources :schedules
  resources :users
  resources :scanned_ports do
    collection do
      get 'datatable' # pagination
    end
  end
  resources :organizations do
    member do
      post 'report'
    end
  end

  resources :user_sessions, only: [:create, :destroy]

  delete '/sign_out', to: 'user_sessions#destroy', as: :sign_out
  get '/sign_in', to: 'user_sessions#new', as: :sign_in

  resource :users_roles

  get '/service_tasks', to: 'service_tasks#index', as: :service_tasks
  post '/service_tasks/clean_base', to: 'service_tasks#clean_base', as: :clean_base_task
  post '/service_tasks/sqlite_backup', to: 'service_tasks#sqlite_backup', as: :sqlite_backup_task

  get '/detected_services', to: 'dashboard#detected_services', as: :detected_services
  get '/dashboard/datatable', to: 'dashboard#datatable'
  get '/dashboard/datatable2', to: 'dashboard#datatable2'
  get '/new_services', to: 'dashboard#new_services', as: :new_services
  get '/hosts', to: 'dashboard#hosts', as: :hosts

end

app/controllers/dj_manager_controller.rb
class DjManagerController < ApplicationController
  def index
    authorize :dj_manager
    #@tasks = Delayed::Job.all
    #@tasks = policy_scope(Delayed::Job)#.includes(:jobs)
    @tasks = DjManagerPolicy::Scope.new(current_user, Delayed::Job).resolve
  end

  def show
    authorize :dj_manager
    if current_user.has_role? :admin
      @task = Delayed::Job.where(id: params[:id]).first
    else
      tasks = DjManagerPolicy::Scope.new(current_user, Delayed::Job).resolve
      if tasks.include? Delayed::Job.where(id: params[:id]).first
        @task = Delayed::Job.where(id: params[:id]).first
      end
    end
    redirect_to dj_index_path unless @task
  end

  def destroy
    authorize :dj_manager
    if current_user.has_role? :admin
      task = Delayed::Job.where(id: params[:id]).where('locked_by IS NULL').first
    else
      tasks = DjManagerPolicy::Scope.new(current_user, Delayed::Job).resolve
      if tasks.include? Delayed::Job.where(id: params[:id]).first
        task = Delayed::Job.where(id: params[:id]).where('locked_by IS NULL').first
      end
    end
    task.destroy if task
    redirect_to dj_index_path
  end

  def create_planner
    authorize :dj_manager
    planner = Delayed::Job.where(queue: 'planner').first
    if planner.blank?
      DailyPlannerJob.perform_later
    end
    redirect_to dj_index_path
  end

  def destroy_all
    authorize :dj_manager
    Delayed::Job.where('locked_by IS NULL').destroy_all
    redirect_to dj_index_path
  end
end

app/helpers/dj_manager_helper.rb
module DjManagerHelper
  def planner_stopped?
    Delayed::Job.where(queue: 'planner').first.blank?
  end
end

app/views/dj_manager/index.html.slim
- if planner_stopped?
  h2
    span.text-danger = t('messages.dj_planner_attention')

h3
  span.text-primary = t('navigations.dj_index')
table.display.table.table-striped.table-bordered#index_table
  thead
    tr
      th.default_sort data-sort = 'desc' ID
      th = t('navigations.dj_queue')
      th = Job.model_name.human
      th = t('navigations.dj_planned_start_time')
      th = t('navigations.dj_locked_at')
      th = t('navigations.dj_locked_by')
      th = t('navigations.dj_last_error')
      th = t('navigations.dj_failed_at')
      th = t('navigations.dj_attempts')
      th

  tbody
    - @tasks.each do |row|
      tr
        td = row.id
        td = row.queue
        td
          - job = Job.find_by_dj_id(row.id)
          - if job.present?
            = link_to job.name, job, class: 'btn btn-link btn-xs'
        td = row.run_at.strftime("%d.%m.%Y:%H.%M")
        td = row.locked_at.strftime("%d.%m.%Y:%H.%M") if row.locked_at
        td = row.locked_by
        td = row.last_error
        td = row.failed_at.strftime("%d.%m.%Y:%H.%M") if row.failed_at
        td = row.attempts
        td
          = link_to t('actions.view'), dj_show_path(row), class: 'btn btn-link btn-xs'
          =< link_to t('actions.delete'), dj_delete_path(row), class: 'btn btn-link btn-xs', method: :delete, data: {confirm: t('actions.confirm')}

= link_to dj_create_planner_path, method: :post do
 span.btn.btn-success
   = t('actions.dj_create_planner')
=< link_to dj_delete_all_path(@task), method: :delete, data: {confirm: t('actions.confirm')} do
 span.btn.btn-danger
  = t('actions.dj_delete_all')

app/views/dj_manager/show.html.slim
.col-sm-offset-1.col-sm-11
  table.table.table-striped.table-hover
    caption.text-primary
      h3 = t('navigations.dj_show')
    thead
      th.col-md-1
      th.col-md-7
    tbody
      tr
        td.text-right.text-info
          strong ID
        td
          = @task.id
      tr
        td.text-right.text-info
          strong
            = t('navigations.dj_queue')
        td
          = @task.queue
      tr
        td.text-right.text-info
          strong
            = t('navigations.dj_created_at')
        td
          = @task.created_at.strftime("%d.%m.%Y:%H.%M")
      tr
        td.text-right.text-info
          strong
            = t('navigations.dj_updated_at')
        td
          = @task.updated_at.strftime("%d.%m.%Y:%H.%M")
      tr
        td.text-right.text-info
          strong
            = t('navigations.dj_planned_start_time')
        td
          = @task.run_at.strftime("%d.%m.%Y:%H.%M") if @task.run_at
      tr
        td.text-right.text-info
          strong
            = t('navigations.dj_locked_at')
        td
          = @task.locked_at.strftime("%d.%m.%Y:%H.%M") if @task.locked_at
      tr
        td.text-right.text-info
          strong
            = t('navigations.dj_locked_by')
        td
          = @task.locked_by
      tr
        td.text-right.text-info
          strong
            = t('navigations.dj_last_error')
        td
          = @task.last_error
      tr
        td.text-right.text-info
          strong
            = t('navigations.dj_failed_at')
        td
          = @task.failed_at.strftime("%d.%m.%Y:%H.%M") if @task.failed_at
      tr
        td.text-right.text-info
          strong
            = t('navigations.dj_attempts')
        td
          = @task.attempts
      tr
        td.text-right.text-info
          strong
            = t('navigations.dj_handler')

        td
          = YAML.load(@task.handler)

= link_to dj_index_path do
  span.btn.btn-info
    = t('navigations.dj_index')
=< link_to dj_delete_path(@task), method: :delete, data: {confirm: t('actions.confirm')} do
  span.btn.btn-danger
    = t('actions.delete')