config/routes.rb
Rails.application.routes.draw do
  root 'organizations#index'

  get '/user_protocols', to: 'user_protocols#index', as: :protocols
  delete '/user_protocols', to: 'user_protocols#destroy_all', as: :protocols_destroy_all

  get 'dj_manager/index', as: :dj_index
  get 'dj_manager/:id' => "dj_manager#show", as: :dj_show

  post 'dj_manager/create_planner' => "dj_manager#create_planner", as: :dj_create_planner
  delete 'dj_manager/:id/destroy' => "dj_manager#destroy", as: :dj_delete
  delete 'dj_manager/destroy_all', as: :dj_delete_all

  resources :option_sets
  resources :services do
    collection do
      get 'datatable' # pagination
    end
    member do
      get 'legalise'
      get 'unlegalise'
    end
  end
  resources :jobs do
    member do
      get 'scan'
    end
  end
  resources :schedules
  resources :users
  resources :scanned_ports do
    collection do
      get 'datatable' # pagination
    end
  end
  resources :organizations do
    member do
      post 'report'
    end
  end

  resources :user_sessions, only: [:create, :destroy]

  delete '/sign_out', to: 'user_sessions#destroy', as: :sign_out
  get '/sign_in', to: 'user_sessions#new', as: :sign_in

  resource :users_roles

  get '/service_tasks', to: 'service_tasks#index', as: :service_tasks
  post '/service_tasks/clean_base', to: 'service_tasks#clean_base', as: :clean_base_task
  post '/service_tasks/sqlite_backup', to: 'service_tasks#sqlite_backup', as: :sqlite_backup_task

  get '/detected_services', to: 'dashboard#detected_services', as: :detected_services
  get '/dashboard/datatable', to: 'dashboard#datatable'
  get '/dashboard/datatable2', to: 'dashboard#datatable2'
  get '/new_services', to: 'dashboard#new_services', as: :new_services
  get '/hosts', to: 'dashboard#hosts', as: :hosts

end

app/models/option_set.rb
class OptionSet < ActiveRecord::Base
  NMAP_OPTIONS = {syn_scan: 'sS',
                  skip_discovery: 'Pn',
                  udp_scan: 'sU',
                  service_scan: 'sV',
                  os_fingerprint: 'O',
                  top_ports: '--top-ports',
                  aggressive_timing: 'T4',
                  insane_timing: 'T5',
                  disable_dns: 'n'}.freeze


  attr_accessor :syn_scan,
                :skip_discovery,
                :udp_scan,
                :os_fingerprint,
                :service_scan,
                :top_ports,
                :aggressive_timing,
                :insane_timing,
                :disable_dns

  before_save :set_options

  serialize :options, Hash

  has_many :jobs, dependent: :destroy

  validates :name, length: {minimum: 3, maximum: 255}
  validates :top_ports, inclusion: {in: 1..1000}, allow_blank: true

  def show_options
    result = options.select do |key, value|
      if key == :top_ports
        value
      else
        value != '0'
      end
    end
    result = result.map do |key, value|
      if key == :top_ports && value.present?
        "--top-ports #{value}"
      else
        "-#{NMAP_OPTIONS[key]} (#{key})"
      end
    end
    result = result.join(', ')
    result
  end

  def syn_scan
    options[:syn_scan]
  end

  def syn_scan=(value)
    options[:syn_scan] = value
  end

  def skip_discovery
    options[:skip_discovery]
  end

  def skip_discovery=(value)
    options[:skip_discovery] = value
  end

  def udp_scan
    options[:udp_scan]
  end

  def udp_scan=(value)
    options[:udp_scan] = value
  end

  def os_fingerprint
    options[:os_fingerprint]
  end

  def os_fingerprint=(value)
    options[:os_fingerprint] = value
  end

  def service_scan
    options[:service_scan]
  end

  def service_scan=(value)
    options[:service_scan] = value
  end

  def top_ports
    options[:top_ports]
  end

  def top_ports=(value)
    options[:top_ports] = value.present? ? value.to_i : nil
  end

  def aggressive_timing
    options[:aggressive_timing]
  end

  def aggressive_timing=(value)
    options[:aggressive_timing] = value
  end

  def insane_timing
    options[:insane_timing]
  end

  def insane_timing=(value)
    options[:insane_timing] = value
  end

  def disable_dns
    options[:disable_dns]
  end

  def disable_dns=(value)
    options[:disable_dns] = value
  end

  private

  def set_options
    self.options = {syn_scan: syn_scan,
                    skip_discovery: skip_discovery,
                    udp_scan: udp_scan,
                    service_scan: service_scan,
                    os_fingerprint: os_fingerprint,
                    top_ports: top_ports,
                    aggressive_timing: aggressive_timing,
                    insane_timing: insane_timing,
                    disable_dns: disable_dns}
  end
end

app/controllers/option_sets_controller.rb
class OptionSetsController < ApplicationController
   before_action :set_option_set, only: [:show, :edit, :update, :destroy]

  # GET /option_sets
  # GET /option_sets.json
  def index
    authorize OptionSet
    @option_sets = OptionSet.all
  end

  # GET /option_sets/1
  # GET /option_sets/1.json
  def show
    authorize @option_set
  end

  # GET /option_sets/new
  def new
    authorize OptionSet
    @option_set = OptionSet.new
  end

  # GET /option_sets/1/edit
  def edit
    authorize @option_set
  end

  # POST /option_sets
  # POST /option_sets.json
  def create
    @option_set = OptionSet.new(option_set_params)
    authorize @option_set
    respond_to do |format|
      if @option_set.save
        flash[:success] = t('flashes.create', model: OptionSet.model_name.human)
        format.html { redirect_to @option_set}
        format.json { render :show, status: :created, location: @option_set }
        protocol_action("создание опций #{@option_set.name}")
      else
        format.html { render :new }
        format.json { render json: @option_set.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /option_sets/1
  # PATCH/PUT /option_sets/1.json
  def update
    authorize @option_set
    respond_to do |format|
      if @option_set.update(option_set_params)
        flash[:success] = t('flashes.update', model: OptionSet.model_name.human)
        format.html { redirect_to @option_set}
        format.json { render :show, status: :ok, location: @option_set }
        protocol_action("редактирование опций #{@option_set.name}")
      else
        format.html { render :edit }
        format.json { render json: @option_set.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /option_sets/1
  # DELETE /option_sets/1.json
  def destroy
    authorize @option_set
    @option_set.destroy
    protocol_action("удаление опций #{@option_set.name}")
    respond_to do |format|
      flash[:success] = t('flashes.destroy', model: OptionSet.model_name.human)
      format.html { redirect_to option_sets_url}
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_option_set
      @option_set = OptionSet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def option_set_params
      params.require(:option_set).permit(:name,
                                         :description,
                                         :options,
                                         :syn_scan,
                                         :skip_discovery,
                                         :udp_scan,
                                         :service_scan,
                                         :os_fingerprint,
                                         :top_ports,
                                         :aggressive_timing,
                                         :insane_timing,
                                         :disable_dns)
    end
end

app/helpers/option_sets_helper.rb
module OptionSetsHelper
end

app/views/option_sets/_form.html.slim
= form_for @option_set, html: {class: 'form-horizontal'} do |f|
  - if @option_set.errors.any?
    .col-sm-offset-1.col-sm-11
      #error_explanation
        h2 = t('errors.template.header', count: @option_set.errors.count, model: OptionSet.model_name.human)
        ul
          - @option_set.errors.full_messages.each do |message|
            li = message

  .form-group
    = f.label :name, class: 'col-sm-2 control-label required'
    .col-sm-10
        = f.text_field :name, class: 'form-control', placeholder: 'название'
  .form-group
    .col-sm-offset-2.col-sm-10
      .checkbox
         label
           = f.check_box :syn_scan
           | syn scan (-sS)
  .form-group
    .col-sm-offset-2.col-sm-10
      .checkbox
         label
           = f.check_box :skip_discovery
           | skip ping discovery (-Pn)
  .form-group
    .col-sm-offset-2.col-sm-10
      .checkbox
         label
           = f.check_box :udp_scan
           | UDP Scan (-SU)
  .form-group
    .col-sm-offset-2.col-sm-10
      .checkbox
         label
           = f.check_box :os_fingerprint
           | OS detection (-O)
  .form-group
    .col-sm-offset-2.col-sm-10
      .checkbox
         label
           = f.check_box :service_scan
           | service scan (-sV)
  .form-group
    .col-sm-offset-2.col-sm-10
      .checkbox
         label
           = f.check_box :aggressive_timing
           | aggressive timing (-T4)
  .form-group
    .col-sm-offset-2.col-sm-10
      .checkbox
         label
           = f.check_box :insane_timing
           | insane timing (-T5)
  .form-group
    .col-sm-offset-2.col-sm-10
      .checkbox
         label
           = f.check_box :disable_dns
           | disable dns (-n)
  .form-group
    = f.label :top_ports,'--top-ports', class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :top_ports, class: 'form-control', placeholder: 'количество портов (1-1000)'
  .form-group
    = f.label :description, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_area :description, rows: 6, class: 'form-control', placeholder: 'дополнительная информация'
  .actions.form-group
    .col-sm-offset-2.col-sm-10
      => link_to option_sets_path do
        span.btn.btn-info = OptionSet.model_name.human count: 2
      = f.submit t('actions.create'), class: 'btn btn-success'

app/views/option_sets/edit.html.slim
.col-sm-offset-1.col-sm-11
  h3
    span.text-primary = "#{t('actions.edit')} #{OptionSet.model_name.human}"

== render 'form'

app/views/option_sets/index.html.slim
h3
  span.text-primary = OptionSet.model_name.human count: 2

table.display.table.table-striped.table-bordered#index_table
  thead
    tr
      th.w45 = t('activerecord.attributes.option_set.name')
      th.w50 = t('activerecord.attributes.option_set.options')
      th.w5

  tbody
    - @option_sets.each do |row|
      tr
        td = link_to row.name, row, class: 'btn btn-link btn-xs'
        td = row.show_options
        td
          = link_to row, class: 'btn btn-default btn-xs', 'data-toggle' => 'tooltip', 'data-placement' => 'top', title: t('actions.view') do
            i.glyphicon.glyphicon-info-sign aria-hidden="true"
          = link_to edit_option_set_path(row), class: 'btn btn-default btn-xs', 'data-toggle' => 'tooltip', 'data-placement' => 'top', title: t('actions.edit') do
            i.glyphicon.glyphicon-edit aria-hidden="true"
          = link_to row, data: {confirm: t('actions.confirm')}, :method => :delete, class: 'btn btn-default btn-xs', 'data-toggle' => 'tooltip', 'data-placement' => 'top', title: t('actions.delete') do
            i.glyphicon.glyphicon-trash aria-hidden="true"

br

= link_to new_option_set_path do
  span.btn.btn-success = t('helpers.submit.create', model: OptionSet.model_name.human)
    i.glyphicon.glyphicon-info-sign aria-hidden="true"

app/views/option_sets/new.html.slim
.col-sm-offset-1.col-sm-11
  h3
    span.text-primary = "#{t('actions.new')} #{OptionSet.model_name.human}"

== render 'form'

app/views/option_sets/show.html.slim
.col-sm-offset-1.col-sm-11
  table.table.table-striped.table-hover
    caption.text-primary
      h3 = OptionSet.model_name.human
    thead
      th.col-md-1
      th.col-md-7
    tbody
      tr
        td.text-right.text-info
          strong
            = OptionSet.human_attribute_name :name
        td
          = @option_set.name
      tr
        td.text-right.text-info
          strong
            = OptionSet.human_attribute_name :options
        td
          = @option_set.show_options
      tr
        td.text-right.text-info
          strong
            = OptionSet.human_attribute_name :description
        td
          = @option_set.description

  => link_to option_sets_path do
    span.btn.btn-info
      = OptionSet.model_name.human count: 2
  = link_to edit_option_set_path(@option_set) do
    span.btn.btn-warning
      = t('actions.edit')