config/routes.rb
Rails.application.routes.draw do
  root 'organizations#index'

  get '/user_protocols', to: 'user_protocols#index', as: :protocols
  delete '/user_protocols', to: 'user_protocols#destroy_all', as: :protocols_destroy_all

  get 'dj_manager/index', as: :dj_index
  get 'dj_manager/:id' => "dj_manager#show", as: :dj_show

  post 'dj_manager/create_planner' => "dj_manager#create_planner", as: :dj_create_planner
  delete 'dj_manager/:id/destroy' => "dj_manager#destroy", as: :dj_delete
  delete 'dj_manager/destroy_all', as: :dj_delete_all

  resources :option_sets
  resources :services do
    collection do
      get 'datatable' # pagination
    end
    member do
      get 'legalise'
      get 'unlegalise'
    end
  end
  resources :jobs do
    member do
      get 'scan'
    end
  end
  resources :schedules
  resources :users
  resources :scanned_ports do
    collection do
      get 'datatable' # pagination
    end
  end
  resources :organizations do
    member do
      post 'report'
    end
  end

  resources :user_sessions, only: [:create, :destroy]

  delete '/sign_out', to: 'user_sessions#destroy', as: :sign_out
  get '/sign_in', to: 'user_sessions#new', as: :sign_in

  resource :users_roles

  get '/service_tasks', to: 'service_tasks#index', as: :service_tasks
  post '/service_tasks/clean_base', to: 'service_tasks#clean_base', as: :clean_base_task
  post '/service_tasks/sqlite_backup', to: 'service_tasks#sqlite_backup', as: :sqlite_backup_task

  get '/detected_services', to: 'dashboard#detected_services', as: :detected_services
  get '/dashboard/datatable', to: 'dashboard#datatable'
  get '/dashboard/datatable2', to: 'dashboard#datatable2'
  get '/new_services', to: 'dashboard#new_services', as: :new_services
  get '/hosts', to: 'dashboard#hosts', as: :hosts

end

app/models/schedule.rb
class Schedule < ActiveRecord::Base

  validates :job_id, numericality: {only_integer: true}
  #validates :week_day, numericality: {only_integer: true, allow_blank: true}
  validates :week_day, inclusion: {in: 0..6, allow_blank: true}
  validates :week_day, uniqueness: {scope: [:job_id, :month_day]}
  #validates :month_day, numericality: {only_integer: true, allow_blank: true}
  validates :month_day, inclusion: {in: 1..31, allow_blank: true}
  validates :month_day, uniqueness: {scope: [:job_id, :week_day]}

  belongs_to :job
  
  def show_week_day
    if self.week_day.present?
      I18n.t('date.day_names')[self.week_day]
    else
      ''
    end
  end
=begin
  def show_week_day
    if self.week_day.present?
      t('date.days_names')[self.week_day]
    else
      ''
    end
  end

  def self.week_days
    t('date.days_names')
  end

  def self.month_days
    1..31
  end
=end

end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :set_schedule, only: [:show, :edit, :update, :destroy]
  before_action :set_job, only: [:create, :destroy]

  # GET /schedules
  # GET /schedules.json
  def index
    authorize Schedule
    @schedules = policy_scope Schedule
    @schedules = @schedules.includes(:job)
  end

  # GET /schedules/1
  # GET /schedules/1.json
  def show
  end

  # GET /schedules/new
  def new
    @schedule = Schedule.new
  end

  # GET /schedules/1/edit
  def edit
  end

  # POST /schedules
  # POST /schedules.json
  def create
    params[:schedule] = {}
    params[:schedule][:job_id] = params[:job_id]
    params[:schedule][:week_day] = params[:week_day]
    params[:schedule][:month_day] = params[:month_day]
    @schedule = Schedule.new(schedule_params)
    authorize @schedule

    respond_to do |format|
      if @schedule.save
        format.html { redirect_to @schedule, notice: 'Schedule was successfully created.' }
        format.json { render :show, status: :created, location: @schedule }
        # возращается ответ на ajax запрос (запрос со страницы сведений о работе)
        format.js {render 'job_schedules_renew'}
      else
        format.html { render :new }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schedules/1
  # PATCH/PUT /schedules/1.json
  def update
    respond_to do |format|
      if @schedule.update(schedule_params)
        format.html { redirect_to @schedule, notice: 'Schedule was successfully updated.' }
        format.json { render :show, status: :ok, location: @schedule }
      else
        format.html { render :edit }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schedules/1
  # DELETE /schedules/1.json
  def destroy
    authorize @schedule
    @schedule.destroy
    respond_to do |format|
      format.html { redirect_to schedules_url, notice: 'Schedule was successfully destroyed.' }
      format.json { head :no_content }
      format.js {render 'job_schedules_renew'}
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_schedule
      @schedule = Schedule.find(params[:id])
    end

    def set_job
      @job = Job.find(params[:job_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def schedule_params
      params.require(:schedule).permit(:job_id, :week_day, :month_day)
    end
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/schedules/_form.html.slim
= form_for @schedule do |f|
  - if @schedule.errors.any?
    #error_explanation
      h2 = "#{pluralize(@schedule.errors.count, "error")} prohibited this schedule from being saved:"
      ul
        - @schedule.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :job
    = f.text_field :job
  .field
    = f.label :week_day
    = f.number_field :week_day
  .field
    = f.label :month_day
    = f.number_field :month_day
  .actions = f.submit

app/views/schedules/_job_schedules.html.slim
#ajax_renewable
  table.table.table-bordered.table-condensed
    caption
      span.text-success
        = t('navigations.week_days')
    tbody
      tr
       - (0..6).each do |day_number|
         - if schedule = Schedule.where(job_id: @job.id, week_day: day_number).first
           td.success
             = link_to schedule_path(schedule, job_id: @job.id ), remote: true, :method => :delete, class: 'btn btn-link', 'data-toggle' => 'tooltip', 'data-placement' => 'top', title: t('actions.delete') do
               i.glyphicon.glyphicon-ok aria-hidden="true"
               =< t('date.day_names')[day_number]
         - else
           td.danger
             = link_to schedules_path(job_id: @job.id, week_day: day_number), remote: true, method: :post, class: 'btn btn-link', 'data-toggle' => 'tooltip', 'data-placement' => 'top', title: t('actions.add')  do
               i.glyphicon.glyphicon-remove aria-hidden="true"
               =< t('date.day_names')[day_number]

app/views/schedules/edit.html.slim
h1 Editing schedule

== render 'form'

= link_to 'Show', @schedule
'|
= link_to 'Back', schedules_path

app/views/schedules/index.html.slim
h3
  span.text-primary = Schedule.model_name.human count: 2

table.display.table.table-striped.table-bordered#index_table
  thead
    tr
      th = t('activerecord.attributes.job.name')
      th.w15 = t('activerecord.attributes.schedule.week_day')
      th.w15 = t('activerecord.attributes.schedule.month_day')

  tbody
    - @schedules.each do |schedule|
      tr
        td = link_to schedule.job.name, schedule.job, class: 'btn btn-link btn-xs'
        td = schedule.show_week_day
        td = schedule.month_day

app/views/schedules/job_schedules_renew.js.erb
$("#ajax_renewable").html("<%= escape_javascript(render partial: 'job_schedules') %>");

app/views/schedules/new.html.slim
h1 New schedule

== render 'form'

= link_to 'Back', schedules_path

app/views/schedules/show.html.slim
p#notice = notice

p
  strong Job:
  = @schedule.job
p
  strong Week day:
  = @schedule.week_day
p
  strong Month day:
  = @schedule.month_day

= link_to 'Edit', edit_schedule_path(@schedule)
'|
= link_to 'Back', schedules_path